#ifndef MAIN_BUTTONS_H
#define MAIN_BUTTONS_H

#define ID_BTN_START 1
#define ID_BTN_EXIT 2
#define ID_BTN_BACK 3
#define ID_STATIC_LABEL 100
#define ID_STATIC_CREDIT 101

#define ID_BTN_INPUT_FIRST 102
#define ID_BTN_INPUT_SECOND 103

#define ID_STATIC_TYPE_FIRST 104
#define ID_STATIC_TYPE_SECOND 105

#define ID_STATIC_RESULT_FIRST 106
#define ID_STATIC_RESULT_SECOND 107

#define ID_BTN_COPY_FIRST 108
#define ID_BTN_COPY_SECOND 109

#define ID_BTN_DETERMINANT_FIRST 110
#define ID_BTN_INVERSE_FIRST 111
#define ID_BTN_TRANSPOSE_FIRST 112
#define ID_BTN_RANK_FIRST 113
#define ID_BTN_MULTIPLY_FIRST 114
#define ID_BTN_POWER_FIRST 115

#define ID_BTN_DETERMINANT_SECOND 116
#define ID_BTN_INVERSE_SECOND 117
#define ID_BTN_TRANSPOSE_SECOND 118
#define ID_BTN_RANK_SECOND 119
#define ID_BTN_MULTIPLY_SECOND 120
#define ID_BTN_POWER_SECOND 121

#define ID_BTN_LENGTH_FIRST 130
#define ID_BTN_MULTIPLY_VECTOR_FIRST 131
#define ID_BTN_POWER_VECTOR_FIRST 132

#define ID_BTN_LENGTH_SECOND 133
#define ID_BTN_MULTIPLY_VECTOR_SECOND 134
#define ID_BTN_POWER_VECTOR_SECOND 135

#define ID_BTN_MATRIX_MULTIPLY 200
#define ID_BTN_MATRIX_ADD 201
#define ID_BTN_MATRIX_SUBTRACT 202

#define ID_BTN_VECTOR_ADD 203
#define ID_BTN_VECTOR_SUBTRACT 204
#define ID_BTN_VECTOR_DOT 205
#define ID_BTN_VECTOR_CROSS 206
#define ID_BTN_VECTOR_MIXED 207

#define ID_BTN_MATRIX_VECTOR_MULTIPLY 208

#endif