#define ID_DIALOG 200
#define ID_EDIT_INPUT 201
#define ID_RADIO_VECTOR 202
#define ID_RADIO_MATRIX 203
#define ID_BTN_OK 204
#define ID_BTN_CANCEL 205
#define ID_BTN_NEXT 206
#define ID_STATIC_ROWS 207
#define ID_STATIC_COLS 208
#define ID_EDIT_ROWS 209
#define ID_EDIT_COLS 210
#define ID_STATIC_INPUT 211
#define ID_STATIC_RESULT_FIRST 104
#define ID_STATIC_RESULT_SECOND 105
#define IDI_APP_ICON 3001
#define IDB_LOGO 999

#define IDD_TRANSPOSE_RESULT 300
#define ID_STATIC_RESULT 301
#define ID_BTN_COPY 302
#define ID_BTN_PASTE_FIRST 303
#define ID_BTN_OK 305

#define IDD_SCALAR_INPUT 400
#define IDD_SCALAR_RESULT 401

#define ID_STATIC_SCALAR 402
#define ID_EDIT_SCALAR 403
#define ID_STATIC_RESULT 404
#define ID_BTN_COPY 405
#define ID_BTN_PASTE_FIRST 406
#define ID_BTN_OK 407
#define ID_BTN_CANCEL 408

#define IDD_POWER_INPUT 409
#define IDD_POWER_RESULT 410

#define ID_STATIC_POWER 411
#define ID_EDIT_POWER 412
#define ID_STATIC_POWER_RESULT 413
#define ID_BTN_COPY_POWER 414
#define ID_BTN_PASTE_POWER_FIRST 415

#define IDD_DETERMINANT_RESULT 416

#define ID_STATIC_DETERMINANT_RESULT 417
#define ID_BTN_COPY_DETERMINANT 418

#define IDD_VECTOR_LENGTH_RESULT 420

#define ID_STATIC_VECTOR_LENGTH_RESULT 421
#define ID_BTN_COPY_VECTOR_LENGTH 422

#define IDD_INVERSE_RESULT 423

#define ID_STATIC_INVERSE_RESULT 424
#define ID_BTN_COPY_INVERSE 425
#define ID_BTN_PASTE_INVERSE_FIRST 426

#define IDD_RANK_RESULT 427
#define ID_STATIC_RANK_RESULT 428
#define ID_BTN_COPY_RANK 429

#define IDD_MATRIX_OP_RESULT 430
#define ID_STATIC_MATRIX_OP_RESULT 431
#define ID_BTN_COPY_MATRIX_OP 432
#define ID_BTN_PASTE_MATRIX_OP_FIRST 433
#define ID_BTN_PASTE_MATRIX_OP_SECOND 434
#define ID_BTN_OK_MATRIX_OP 435

#define IDD_VECTOR_OP_RESULT 436
#define ID_STATIC_VECTOR_OP_RESULT 437
#define ID_BTN_COPY_VECTOR_OP 438
#define ID_BTN_PASTE_VECTOR_OP_FIRST 439
#define ID_BTN_PASTE_VECTOR_OP_SECOND 440
#define ID_BTN_OK_VECTOR_OP 441

#define IDD_VECTOR_PROD_RESULT 442
#define ID_STATIC_VECTOR_PROD_RESULT 443
#define ID_BTN_COPY_VECTOR_PROD 444
#define ID_BTN_OK_VECTOR_PROD 445
